### ISSUE TITLE
你好，我也在搞本地模型，这个通过flask提供api服务吗，做一个chat接口

### ISSUE THREAD

**Issue by yanyuxiyangzk** [zhongpei/ChatGLM-Chinese-Summary#1]

**Comment by zhongpei** [comment]
目前chatglm的http api模式已经有多个项目了，比如https://github.com/ninehills/chatglm-openai-api，本项目主要是做chatglm中文摘要方面的尝试，以代替gpt4来实现本地长文章摘要。
